- name: Install nginx
  ansible.builtin.package:
    name: nginx

- name: Copy static contents
  ansible.builtin.copy:
    src: static/
    dest: /var/www/html/

- name: Create an index image
  ansible.builtin.template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html

- name: Create an nginx config
  ansible.builtin.copy:
    src: conf/default
    dest: /etc/nginx/sites-enabled/default
  notify: Reload nginx