{
 "title": "Nginx",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Rate / Errors / Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Successes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_requests_total{code=\"1xx\", host=\"*\"}[$__rate_interval]))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum(rate(nginx_vts_server_requests_total{code=\"2xx\", host=\"*\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(nginx_vts_server_requests_total{code=\"3xx\", host=\"*\"}[$__rate_interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(nginx_vts_server_requests_total{code=\"4xx\", host=\"*\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "Timings at percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_vts_server_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(nginx_vts_server_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(nginx_vts_server_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "75%"
    }
   ]
  },
  {
   "title": "Utilisation / Saturation / Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum by(mode) (rate(node_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_server_requests_total{code=\"5xx\", host=\"*\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "CPU usage per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current alerts",
   "type": "alertlist",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "ALERTS{alertname=\"nginx\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}